// generated by tools/ml2/export_kernel.py from report/models2/final_linear.json
// Default VM_POLICY_ML weights: the global kernel+refault linear model
// chosen on validation (idle+dirty+refaults+rdist, probation 4).
#include "vmstats.h"
static const struct vm_ml_weights ml_default_weights = { 4, { 3, 5, 6, 7, 0, 0, 0, 0 }, { 126, 36, -113, 122, 0, 0, 0, 0 }, 4 };
