#!/usr/bin/env python3
"""Export trained kernel-observable models to the integer form xv6 runs.

  kernel/mlfeat_table.h, kernel/mlfeat_mant.h   integer log1p tables
  kernel/mlweights.h    the default VM_POLICY_ML weights (the global
                        kernel+refault model chosen on validation)
  user/mlmodels.h       every exported model by name, for user/vmrun.c

Weights: qa[j] = round(W[j] / std[j] * 2^8) -- the training-time
standardisation folded in; the mean and bias terms are the same for every
candidate and drop out of the argmax (see kernel/mlfeat.h).

    python3 export_kernel.py
"""
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
KFEAT = ["ref", "aging", "sfreq", "idle", "age", "dirty", "refaults", "rdist"]
Q = 8


def tables():
    small = [round(256 * math.log1p(v)) for v in range(256)]
    mant = [round(256 * math.log(1 + m / 1024)) for m in range(1024)]

    def fmt(a):
        return "\n".join("  " + ", ".join(str(x) for x in a[i:i + 16]) + ","
                         for i in range(0, len(a), 16)) + "\n"
    (ROOT / "kernel" / "mlfeat_table.h").write_text(
        "// generated by tools/ml2/export_kernel.py: round(256 * ln(1 + v)), v = 0..255\n"
        + fmt(small))
    (ROOT / "kernel" / "mlfeat_mant.h").write_text(
        "// generated by tools/ml2/export_kernel.py: round(256 * ln(1 + m / 1024)), m = 0..1023\n"
        + fmt(mant))


def integer(spec):
    """JSON spec (linear, kernel features only) -> (feat ids, qa, protect)."""
    feats = spec["features"]
    assert all(f in KFEAT for f in feats), f"not kernel-observable: {feats}"
    W = spec["layers"][0]["W"][0]
    qa = [int(round(w / sd * (1 << Q))) for w, sd in zip(W, spec["std"])]
    return [KFEAT.index(f) for f in feats], qa, int(spec.get("protect_age", 0))


def c_init(ids, qa, protect):
    pad = ML = len(KFEAT)
    ids_s = ", ".join(str(i) for i in ids + [0] * (ML - len(ids)))
    qa_s = ", ".join(str(q) for q in qa + [0] * (ML - len(qa)))
    return f"{{ {len(ids)}, {{ {ids_s} }}, {{ {qa_s} }}, {protect} }}"


def main():
    tables()
    final = json.load(open(ROOT / "report" / "models2" / "final_linear.json"))
    models = []
    for key, spec in sorted(final.items()):
        scope, group = key.split("|")
        if group not in ("K", "K+K+"):
            continue
        name = scope + ("" if group == "K+K+" else "-k")
        ids, qa, protect = integer(spec)
        models.append((name, key, spec["features"], ids, qa, protect))
    default = next(m for m in models if m[0] == "global")

    k = ["// generated by tools/ml2/export_kernel.py from report/models2/final_linear.json",
         "// Default VM_POLICY_ML weights: the global kernel+refault linear model",
         f"// chosen on validation ({'+'.join(default[2])}, probation {default[5]}).",
         "#include \"vmstats.h\"",
         f"static const struct vm_ml_weights ml_default_weights = {c_init(*default[3:])};", ""]
    (ROOT / "kernel" / "mlweights.h").write_text("\n".join(k))

    u = ["// generated by tools/ml2/export_kernel.py from report/models2/final_linear.json",
         "// Every exported kernel-observable model; \"<workload>\" is the kernel+refault",
         "// tier, \"<workload>-k\" the kernel-only tier, \"global\" the model trained on all.",
         "#include \"kernel/vmstats.h\"",
         "struct ml_model { const char *name; struct vm_ml_weights w; };",
         "static const struct ml_model ml_models[] = {"]
    for name, key, feats, ids, qa, protect in models:
        u.append(f"  {{ \"{name}\", {c_init(ids, qa, protect)} }},  // {'+'.join(feats)}")
    u += ["};", "#define ML_NMODELS (sizeof(ml_models) / sizeof(ml_models[0]))", ""]
    (ROOT / "user" / "mlmodels.h").write_text("\n".join(u))
    for name, key, feats, ids, qa, protect in models:
        print(f"  {name:<10} {'+'.join(feats):<45} qa={qa} probation={protect}")


if __name__ == "__main__":
    main()
