#!/usr/bin/env python3
"""Known-answer checks for patbench's patterns in the simulator
(GAWWY_HANDOFF_NEW_BENCHMARKS.md, section 8 check 6).

    python3 tools/check_patterns.py [--accesses N] [--seed S] [variant ...]

Each pattern's reference string is generated by the host model
(tools/hostmodel/patbench.py), which tools/hostmodel/check_run.py has
shown to be byte-identical to patbench's own traces, and replayed through
tools/sim.py's policies at 5-30% of the pages it touches (and, for loop,
80/90/95/99% as well). Two kinds of expectation:

  CONTROL     a textbook result the simulator must reproduce. A failure
              means a bug in patbench, its model or the simulator:
                loop     LRU and FIFO miss on every access; MRU and Belady
                         miss L - C to L - C + 1 times per warm pass
                uniform  every online policy misses 1 - C/P of accesses
                         (within 0.01); Belady misses fewer
  INFO        loop's Clock. Textbook Clock misses every access on a loop,
              but the kernel's choose_clock() is not textbook Clock: its
              candidates are the owned-frame list in load order, a victim
              is unlinked and the new page appended at the tail, and the
              hand is an index taken modulo the list length, so after each
              eviction it skips a page. sim.py's Clock mirrors that (and
              starts a new page's referenced bit at 0 where the kernel's
              fault sets PTE_A), and close to L it keeps much of the loop
              resident. Printed, not checked.
  PREDICTION  what the handoff expects, reported as holding or not --
              a prediction that fails is a finding, not a bug:
                scanhot  LFU and ARC keep the hot set where LRU and FIFO
                         lose it; Aging is listed as scan-resistant too
                zipf     LFU is the best online policy; Belady's lead
                         over the best online policy shrinks as skew rises
                phase    LFU misses more than LRU and Aging
                switch   no classic policy is best in both phase kinds;
                         ARC is compared against each

Exits non-zero if a CONTROL fails. The default length (200,000 accesses)
is a tenth of a full stream: the expectations are steady-state properties
and sim.py's policies are O(C) per fault.
"""
from __future__ import annotations

import argparse
import os
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from sim import POLICIES, belady_faults_evictions  # noqa: E402
from hostmodel import patbench  # noqa: E402

ONLINE = ["fifo", "clock", "aging", "lru", "lfu", "mru", "arc"]
VARIANTS = ["loop", "scanhot", "scanhotlo", "zipf060", "zipf080", "zipf099",
            "zipf120", "uniform", "phase", "phaseshort", "switch"]
P = 1024
SWEEP = (5, 10, 15, 20, 25, 30)
LOOP_HIGH = (80, 90, 95, 99)


def generate(variant, accesses, seed):
    pages = []
    res = patbench.run([str(P), "0", str(accesses), str(seed), variant],
                       lambda pg, w: pages.append(pg))
    return pages, res


def simulate(name, refs, cap, mark=None):
    """Total faults, and the faults on accesses where mark[i] is true."""
    sim = POLICIES[name](cap)
    marked = 0
    if mark is None:
        for vpn in refs:
            sim.access(vpn)
        return sim.faults, 0
    for vpn, m in zip(refs, mark):
        before = sim.faults
        sim.access(vpn)
        if m and sim.faults != before:
            marked += 1
    return sim.faults, marked


class Report:
    def __init__(self):
        self.control_failures = []
        self.predictions = []

    def control(self, ok, what):
        print("  CONTROL    %-4s %s" % ("ok" if ok else "FAIL", what))
        if not ok:
            self.control_failures.append(what)

    def predict(self, ok, what):
        print("  PREDICTION %-5s %s" % ("holds" if ok else "NOT", what))
        self.predictions.append((ok, what))

    def info(self, what):
        print("  INFO       %s" % what)


def table(rows, caps, policies):
    print("  %-8s" % "C" + "".join("%10s" % p for p in policies))
    for cap in caps:
        print("  %-8d" % cap + "".join("%10d" % rows[cap][p] for p in policies))


def caps_for(distinct, pcts):
    return [max(2, round(distinct * p / 100)) for p in pcts]


def run_variant(variant, accesses, seed, rep, lead_by_theta):
    t0 = time.time()
    if variant == "loop":
        accesses -= accesses % P   # whole passes, so misses per pass are exact
    refs, res = generate(variant, accesses, seed)
    distinct = len(set(refs))
    pcts = SWEEP + (LOOP_HIGH if variant == "loop" else ())
    caps = caps_for(distinct, pcts)
    print("\n== %s: %d accesses, %d pages touched, capacities %s"
          % (variant, len(refs), distinct, caps))

    mark = None
    if variant.startswith("scanhot"):
        rng = patbench.Rng(seed)
        perm_a = patbench.Perm(P, rng.next())
        hot = {perm_a.fwd(j) for j in range(P // patbench.HOT_DIV)}
        mark = [r in hot for r in refs]
    elif variant == "switch":
        k = accesses // 8
        mark = [(i // k) % 2 == 0 for i in range(len(refs))]  # loop phases

    rows, marked = {}, {}
    for cap in caps:
        rows[cap], marked[cap] = {}, {}
        for name in ONLINE:
            rows[cap][name], marked[cap][name] = simulate(name, refs, cap, mark)
        rows[cap]["belady"] = belady_faults_evictions(refs, cap)[0]
    table(rows, caps, ONLINE + ["belady"])
    n = len(refs)

    if variant == "loop":
        L = distinct
        warm = n // L - 1
        for cap in caps:
            r = rows[cap]
            rep.control(r["lru"] == r["fifo"] == n,
                        "C=%d: LRU/FIFO miss all %d accesses (%d/%d)"
                        % (cap, n, r["lru"], r["fifo"]))
            # Belady's steady state on a loop is L(L-C)/(L-1) misses per
            # pass, between L-C and L-C+1; MRU's is L-C.
            for name in ("mru", "belady"):
                per_pass = (r[name] - L) / warm
                rep.control(L - cap <= per_pass <= L - cap + 1,
                            "C=%d: %s %.2f misses per warm pass (L-C = %d)"
                            % (cap, name, per_pass, L - cap))
            rep.info("C=%d: sim.py Clock misses %d of %d (%.1f%%; textbook "
                     "Clock: all)" % (cap, r["clock"], n, 100.0 * r["clock"] / n))
    elif variant == "uniform":
        for cap in caps:
            want = 1 - cap / P
            r = rows[cap]
            off = {p: r[p] / n - want for p in ONLINE}
            worst = max(off, key=lambda p: abs(off[p]))
            rep.control(abs(off[worst]) < 0.01,
                        "C=%d: online miss ratios within 0.01 of 1-C/P = %.4f "
                        "(furthest %s %+.4f)" % (cap, want, worst, off[worst]))
            rep.control(r["belady"] < min(r[p] for p in ONLINE),
                        "C=%d: Belady (%d) below every online policy"
                        % (cap, r["belady"]))
    elif variant.startswith("scanhot"):
        nhot = sum(mark)
        H = P // patbench.HOT_DIV
        print("  hot-page miss ratio (%d hot accesses):" % nhot)
        print("  %-8s" % "C" + "".join("%10s" % p for p in ONLINE))
        for cap in caps:
            print("  %-8d" % cap + "".join("%10.3f" % (marked[cap][p] / nhot) for p in ONLINE))
        for cap in caps:
            if cap < 2 * H:
                continue   # the hot set plus any scan window does not fit
            # "Keeps the hot set": at most half the hot-page misses of the
            # worse of LRU and FIFO. A policy level with LRU does not.
            hm = {p: marked[cap][p] / nhot for p in ONLINE}
            lost = max(hm["lru"], hm["fifo"])
            for p in ("lfu", "arc", "aging"):
                rep.predict(hm[p] <= lost / 2,
                            "C=%d: %s keeps the hot set: hot-miss %.3f vs "
                            "LRU/FIFO's %.3f" % (cap, p, hm[p], lost))
    elif variant.startswith("zipf"):
        theta = int(variant[4:])
        for cap in caps:
            r = rows[cap]
            best = min(ONLINE, key=lambda p: r[p])
            rep.predict(r["lfu"] <= min(r[p] for p in ONLINE),
                        "C=%d: LFU best online (LFU %d, best %s %d)"
                        % (cap, r["lfu"], best, r[best]))
            lead_by_theta.setdefault(cap_index(caps, cap), {})[theta] = \
                (r[best] - r["belady"]) / r[best]
    elif variant.startswith("phase"):
        for cap in caps:
            r = rows[cap]
            rep.predict(r["lfu"] > r["lru"] and r["lfu"] > r["aging"],
                        "C=%d: LFU (%d) misses more than LRU (%d) and Aging (%d)"
                        % (cap, r["lfu"], r["lru"], r["aging"]))
    elif variant == "switch":
        print("  faults in loop phases / zipf phases:")
        for cap in caps:
            lp = {p: marked[cap][p] for p in ONLINE}
            zp = {p: rows[cap][p] - marked[cap][p] for p in ONLINE}
            bl, bz = min(lp, key=lp.get), min(zp, key=zp.get)
            print("  C=%-5d best in loop phases %s (%d), in zipf phases %s (%d); "
                  "ARC %d / %d" % (cap, bl, lp[bl], bz, zp[bz], lp["arc"], zp["arc"]))
            rep.predict(bl != bz,
                        "C=%d: no single classic policy best in both phase kinds"
                        % cap)
    print("  (%.0fs)" % (time.time() - t0))


def cap_index(caps, cap):
    return SWEEP[caps.index(cap)]


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("variants", nargs="*", default=VARIANTS)
    ap.add_argument("--accesses", type=int, default=200000)
    ap.add_argument("--seed", type=int, default=1)
    a = ap.parse_args()
    rep = Report()
    lead = {}
    for v in a.variants:
        if v not in VARIANTS:
            sys.exit("unknown variant %s" % v)
        run_variant(v, a.accesses, a.seed, rep, lead)
    if len({t for d in lead.values() for t in d}) > 1:
        print("\n== zipf: Belady's lead over the best online policy, by skew")
        for pct, by_theta in sorted(lead.items()):
            thetas = sorted(by_theta)
            leads = [by_theta[t] for t in thetas]
            print("  %d%%: " % pct + "  ".join("theta %.2f %.3f" % (t / 100, l)
                                              for t, l in zip(thetas, leads)))
            rep.predict(all(x > y for x, y in zip(leads, leads[1:])),
                        "%d%%: lead shrinks as skew rises" % pct)
    held = sum(ok for ok, _ in rep.predictions)
    print("\npredictions: %d of %d hold" % (held, len(rep.predictions)))
    if rep.control_failures:
        print("CONTROL FAILURES:", *rep.control_failures, sep="\n  ")
        sys.exit(1)
    print("all controls passed")


if __name__ == "__main__":
    main()
