// generated by tools/ml2/export_kernel.py from report/models2/final_linear.json
// Every exported kernel-observable model; "<workload>" is the kernel+refault
// tier, "<workload>-k" the kernel-only tier, "global" the model trained on all.
#include "kernel/vmstats.h"
struct ml_model { const char *name; struct vm_ml_weights w; };
static const struct ml_model ml_models[] = {
  { "btree-k", { 4, { 0, 3, 4, 5, 0, 0, 0, 0 }, { 220, 212, -158, 225, 0, 0, 0, 0 }, 0 } },  // ref+idle+age+dirty
  { "btree", { 5, { 1, 3, 4, 5, 6, 0, 0, 0 }, { 96, 203, -167, 164, -52, 0, 0, 0 }, 0 } },  // aging+idle+age+dirty+refaults
  { "global-k", { 3, { 1, 3, 4, 0, 0, 0, 0, 0 }, { -1087, 110, -59, 0, 0, 0, 0, 0 }, 0 } },  // aging+idle+age
  { "global", { 4, { 3, 5, 6, 7, 0, 0, 0, 0 }, { 126, 36, -113, 122, 0, 0, 0, 0 }, 4 } },  // idle+dirty+refaults+rdist
  { "graph-k", { 3, { 2, 3, 5, 0, 0, 0, 0, 0 }, { -9, 157, -403, 0, 0, 0, 0, 0 }, 4 } },  // sfreq+idle+dirty
  { "graph", { 4, { 2, 3, 5, 7, 0, 0, 0, 0 }, { -2, 159, -347, 24, 0, 0, 0, 0 }, 4 } },  // sfreq+idle+dirty+rdist
  { "kv-k", { 4, { 0, 1, 3, 4, 0, 0, 0, 0 }, { 183, -11, 248, -156, 0, 0, 0, 0 }, 4 } },  // ref+aging+idle+age
  { "kv", { 5, { 1, 3, 5, 6, 7, 0, 0, 0 }, { -76, 157, -97, -51, 102, 0, 0, 0 }, 2 } },  // aging+idle+dirty+refaults+rdist
  { "matmul-k", { 4, { 0, 1, 3, 5, 0, 0, 0, 0 }, { 630, -1853, -194, 248, 0, 0, 0, 0 }, 0 } },  // ref+aging+idle+dirty
  { "matmul", { 5, { 1, 3, 5, 6, 7, 0, 0, 0 }, { 393, 501, 291, 20, 351, 0, 0, 0 }, 0 } },  // aging+idle+dirty+refaults+rdist
  { "sort-k", { 1, { 1, 0, 0, 0, 0, 0, 0, 0 }, { -2255, 0, 0, 0, 0, 0, 0, 0 }, 0 } },  // aging
  { "sort", { 4, { 0, 5, 6, 7, 0, 0, 0, 0 }, { -653, 102, -241, 201, 0, 0, 0, 0 }, 4 } },  // ref+dirty+refaults+rdist
};
#define ML_NMODELS (sizeof(ml_models) / sizeof(ml_models[0]))
