// Run a program under a chosen page-replacement policy.
//
//   vmrun <fifo|clock|aging|lfu|ml> [model] <program> [args...]
//
// For "ml", an optional model name (see user/mlmodels.h, generated by
// tools/ml2/export_kernel.py) selects the weights; without one the kernel's
// default (the global kernel+refault model) is used. The policy and weights
// are per-process state kept across exec, so they apply to the program.
#include "kernel/types.h"
#include "kernel/stat.h"
#include "kernel/vmstats.h"
#include "user/user.h"
#include "user/mlmodels.h"

static const char *names[] = { "fifo", "clock", "aging", "lfu", "ml" };

static void
usage(void)
{
  fprintf(2, "usage: vmrun <fifo|clock|aging|lfu|ml> [model] <program> [args...]\n"
             "models:");
  for(int i = 0; i < ML_NMODELS; i++)
    fprintf(2, " %s", ml_models[i].name);
  fprintf(2, "\n");
  exit(1);
}

int
main(int argc, char **argv)
{
  if(argc < 3)
    usage();
  int policy = -1;
  for(int i = 0; i < sizeof(names) / sizeof(names[0]); i++)
    if(strcmp(argv[1], names[i]) == 0)
      policy = i;
  if(policy < 0)
    usage();
  int prog = 2;
  if(policy == VM_POLICY_ML){
    for(int i = 0; i < ML_NMODELS; i++){
      if(strcmp(argv[2], ml_models[i].name) == 0){
        struct vm_ml_weights w = ml_models[i].w;
        if(vmctl(VM_SET_ML_WEIGHTS, (uint64)&w) < 0){
          fprintf(2, "vmrun: vmctl VM_SET_ML_WEIGHTS failed\n");
          exit(1);
        }
        printf("vmrun: policy=ml model=%s\n", ml_models[i].name);
        prog = 3;
        break;
      }
    }
  }
  if(prog >= argc)
    usage();
  if(vmctl(VM_SET_POLICY, policy) < 0){
    fprintf(2, "vmrun: vmctl VM_SET_POLICY failed\n");
    exit(1);
  }
  exec(argv[prog], argv + prog);
  fprintf(2, "vmrun: exec %s failed\n", argv[prog]);
  exit(1);
}
